name: HACS Action

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    permissions:
      contents: read
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: HACS Action
      uses: "hacs/action@d556e736723344f83838d08488c983a15381059a"  # v22.5.0
      with:
        category: "integration"
